### ISSUE TITLE
where is link to available comfy nodes?

### ISSUE THREAD

**Issue by zenafey** [civitai/civitai-javascript#2]
it is not clickable
![image](https://github.com/civitai/civitai-javascript/assets/118455214/dbd2bff3-ebb3-46e0-b94a-020b8fc01097)

**Comment by bryantanjw** [comment]
The ComfyUI demo site isn't exactly working yet -- we're still working to add ComfyUI workflow support. The demo site is just to showcase a webhook implementation of the SDK.

I'll keep this thread updated once ComfyUI support is added -- should be in the next week or so!

**Comment by bryantanjw** [comment]
heyy, @zenafey! Want to keep this thread updated. We're gonna discard the ComfyUI example in the repo as we're building a better GUI for users to use Civitai models in a ComfyUI interface. In other words, an alternative to ComfyUI that allows you to directly use our models, instead of having to download them to an external machine.

It's still very much a work in progress! You can keep track of the progress here: https://git.new/civitui. We have a short demo there on what to expect. I'll update the thread again once it's ready for user testing :D -- maybe the next couple weeks or so.

**Comment by zenafey** [comment]
> heyy, @zenafey! Want to keep this thread updated. We're gonna discard the ComfyUI example in the repo as we're building a better GUI for users to use Civitai models in a ComfyUI interface. In other words, an alternative to ComfyUI that allows you to directly use our models, instead of having to download them to an external machine.
> 
> It's still very much a work in progress! You can keep track of the progress here: https://git.new/civitui. We have a short demo there on what to expect. I'll update the thread again once it's ready for user testing :D -- maybe the next couple weeks or so.

Great! TY for this information

I think if you gonna discard the comfy example from the repository then this issue makes no sense and should be closed?
